#!/bin/bash

choice=$(printf 'Dracula\nDoomOne\nNord\nNordLight'|dmenu -i -p "Select Theme: ")
if [ -z "$choice" ]; then
    $choice="Dracula"
fi
echo $choice > $XDG_CONFIG_HOME/xmonad/theme.txt

killall xmobar; xmonad --recompile; xmonad --restart
