#!/usr/bin/env sh

shopt -s nullglob globstar

SOURCE_DIR=$(cd -- "$(dirname "${BASH_SOURCE[0]}")" &> /dev/null && pwd)
source "$SOURCE_DIR/common.sh"

DMENU_PROMPT="passname:"
DMENU="dmenu -p $DMENU_PROMPT -l $VERTICAL_ITEM_COUNT -x $DMENU_X -y $DMENU_Y -z $DMENU_WIDTH"

typeit=0
if [[ $1 == "--type" ]]; then
	typeit=1
	shift
fi

if [[ -n $WAYLAND_DISPLAY ]]; then
	dmenu=dmenu-wl
	xdotool="ydotool type --file -"
elif [[ -n $DISPLAY ]]; then
	dmenu="$DMENU" #dmenu
	xdotool="xdotool type --clearmodifiers --file -"
else
	echo "Error: No Wayland or X11 display detected" >&2
	exit 1
fi

prefix=${PASSWORD_STORE_DIR-~/.password-store}
password_files=( "$prefix"/**/*.gpg )
password_files=( "${password_files[@]#"$prefix"/}" )
password_files=( "${password_files[@]%.gpg}" )

password=$(printf '%s\n' "${password_files[@]}" | ${dmenu} "$@")

[[ -n $password ]] || exit

####### My Edits ######
username=$( pass show "$password" |grep -Po "(?<=Username:\s).*")
summary="passmenu"
body="<span color='#57dafd' font='20px'><i>username: </i><b>$username</b></span>"
notify-send -t 10000 "$summary" "$body"
#######################

if [[ $typeit -eq 0 ]]; then
	pass show -c "$password" 2>/dev/null
else
	pass show "$password" | { IFS= read -r pass; printf %s "$pass"; } | $xdotool
fi
