#!/bin/sh

choice=`printf "cancel\nlock\npoweroff\nreboot\nlogout" | dmenu -p "power-menu"`
echo $choice
case "$choice" in
  "poweroff") loginctl poweroff
  ;;
  "reboot") loginctl reboot
  ;;
  "logout") loginctl terminate-user ""
  ;;
  "lock") i3lock -t -e -f -i "$HOME/wallpapers/lock.png"
  ;;
  *) :
  ;;
esac
