#!/bin/bash

choice=$(printf 'cancel\nlock\nlogout\nhibernate\nsuspend\npoweroff\nreboot'|dmenu -i -p "Choose Option")
[ $choice = "cancel"    ] ;
[ $choice = "lock"      ] && dm-tool lock
[ $choice = "logout"    ] && loginctl terminate-user
[ $choice = "poweroff"  ] && poweroff
[ $choice = "reboot"    ] && reboot
[ $choice = "hibernate" ] && systemctl hibernate
[ $choice = "suspend"   ] && systemctl suspend
