#!/bin/sh
# end a command with ; to run in a terminal

SOURCE_DIR=$(cd -- "$(dirname "${BASH_SOURCE[0]}")" &> /dev/null && pwd)
source "$SOURCE_DIR/common.sh"

cachedir=${XDG_CACHE_HOME:-"$HOME/.cache"}
cache="$cachedir/dmenu_recent"

DMENU_PROMPT="run:"
DMENU="dmenu -p $DMENU_PROMPT -l $VERTICAL_ITEM_COUNT -x $DMENU_X -y $DMENU_Y -z $DMENU_WIDTH"

touch "$cache"

# cleaning
while read cmd
do
    command -v ${cmd%;} &>/dev/null || sed -i "/$cmd/d" $cache
done < <(sort -u $cache)

most_used=$(sort "$cache" | uniq -c | sort -rh | sed 's/\s*//' | cut -d' ' -f2-)
run=$((echo "$most_used"; dmenu_path | grep -vxF "$most_used") | $DMENU ) #dmenu -l 25 -i "$@")

[ -z "$run" ] && exit 1

(echo "$run"; head -n 99 "$cache") > "$cache.$$"
mv "$cache.$$" "$cache"

for cmd in "$run"; do ${SHELL:-"/bin/sh"} -c "$cmd" & done
